#!/usr/bin/env bash
# chroma_key.sh — recover a true alpha-channel PNG from a green-screen image
#
# CROSS-PLATFORM NOTE: This script requires bash, ffmpeg, and imagemagick.
# On Windows, use the Python alternative instead:
#   python scripts/chroma_key.py input.png output.png [--key-color #00FF00] [--similarity 0.22]
# The Python version (chroma_key.py) works on all platforms with only Pillow as a dependency.
# generated by a model that can't natively output transparency (Nano Banana /
# Nano Banana Pro / Nano Banana 2, etc).
#
# Usage:
#   ./chroma_key.sh input.png output.png [key_color] [similarity] [blend]
#
#   input.png     source image, subject shot on a flat, saturated backing color
#   output.png    result, real alpha channel, trimmed to bounding box
#   key_color     backing color to remove (default 0x00FF00 pure green)
#   similarity    ffmpeg colorkey similarity 0-1 (default 0.22 — raise if
#                 fringing remains, lower if the subject gets eaten into)
#   blend         ffmpeg colorkey blend 0-1 for edge softness (default 0.08)
#
# Requires: ffmpeg, imagemagick (convert/magick)

set -euo pipefail

INPUT="${1:?input PNG required}"
OUTPUT="${2:?output PNG required}"
KEY_COLOR="${3:-0x00FF00}"
SIMILARITY="${4:-0.22}"
BLEND="${5:-0.08}"

TMP_KEYED="$(mktemp --suffix=.png)"
TMP_DESPILL="$(mktemp --suffix=.png)"

cleanup() { rm -f "$TMP_KEYED" "$TMP_DESPILL"; }
trap cleanup EXIT

echo "[1/3] Keying out ${KEY_COLOR} background..."
ffmpeg -y -loglevel error -i "$INPUT" \
  -vf "colorkey=${KEY_COLOR}:${SIMILARITY}:${BLEND}" \
  "$TMP_KEYED"

echo "[2/3] Removing green spill from edge pixels..."
# despill: pull green channel toward the average of red/blue wherever green
# dominates, so keyed edges don't retain a green fringe
ffmpeg -y -loglevel error -i "$TMP_KEYED" \
  -vf "despill=type=green:mix=0.5:expand=0" \
  "$TMP_DESPILL"

echo "[3/3] Trimming to bounding box..."
if command -v magick >/dev/null 2>&1; then
  magick "$TMP_DESPILL" -trim +repage "$OUTPUT"
else
  convert "$TMP_DESPILL" -trim +repage "$OUTPUT"
fi

# Sanity check: fail loudly if the result has no real transparency, so a bad
# key doesn't silently get composited into the page.
ALPHA_CHECK=$(python3 - "$OUTPUT" <<'PY'
import sys
from PIL import Image
im = Image.open(sys.argv[1]).convert("RGBA")
alphas = im.getchannel("A").getextrema()
print(f"min={alphas[0]} max={alphas[1]}")
PY
)
echo "Alpha channel range: ${ALPHA_CHECK}"
if [[ "$ALPHA_CHECK" == "min=255 max=255" ]]; then
  echo "WARNING: no transparent pixels found — keying likely failed." >&2
  echo "Try raising SIMILARITY, or fall back to white/black difference matting." >&2
  exit 1
fi

echo "Done: $OUTPUT"
